#!/usr/bin/env python3
'''
Terrible openbox auto resolution configuration thingy.

Dependencies:
  sudo package-manager install feh xrandr
  sudo pip3 install parse
'''

import json
import os
import parse
import pprint
import subprocess
import sys
import time

#Parsing ints/floats from left side (ignoring invalid symboles on the right)
def get_from_string_left(string,ch_set='0123456789.'):
	digits=''
	for ch in string:
		if ch not in ch_set:
			break
		digits+=ch
	return digits

#Returns an array of objects that look like (super hacky...):
#  {
#    'name':'HDMI1',                            #Device name
#    'state':'disconnected'|'connected',        #If device is connected or not
#    'primary':True,                            #Is set to as a primary scren
#    'active':['h':2160,'w':3840,'x':0,'y':0],  #Current resolution and position
#    'modes':[{                                 #Listed modes
#      'resolution':[3840,2160],                #Mode resolution
#      'frequencies':[60.00,30.00,24.00]        #Mode frequencies
#    }....],
#    'frequency':60.00,                         #Current set frequency
#    'internal':False                           #Is internal (eDP or LVDS)
#  }
def get_xrandr_info():
	devices=[]
	current_device=None

	#Parse xrandr lines
	for line in subprocess.check_output(['xrandr']).decode('ascii','ignore').strip().split('\n'):
		line=line.rstrip()

		#Display detail line
		if current_device is not None and line.startswith(' '):
			line=line.strip().split()

			#Convert resolutions
			resolution=[]
			for entry in line[0].split('x'):
				digits=get_from_string_left(entry)
				if len(digits)>0:
					resolution.append(int(digits))
			if len(resolution)!=2:
				resolution=None

			#Convert Frequencies
			frequencies=[]
			for entry in line[1:]:
				set_active=entry.endswith('*')
				digits=get_from_string_left(entry)
				if len(digits)>0:
					digits=float(digits)
					frequencies.append(digits)
					current_device['frequency']=digits
			current_device['modes'].append({'resolution':resolution,'frequencies':frequencies})

		#Diplay line
		elif line.find('connected')>=0:
			if current_device is not None:
				devices.append(current_device)
			line=line.strip().split()

			#Check if primary device
			primary=line[2]=='primary'

			#Figure out active and current setting
			active=None
			try:
				active_str=line[2]
				if primary:
					active_str=line[3]
				w,h,x,y=parse.parse('{}x{}+{}+{}',active_str)
				active={'w':int(w),'h':int(h),'x':int(x),'y':int(y)}
			except Exception:
				pass

			#Get name and figure out if internal:
			name=line[0]
			internal=name.startswith('eDP') or name.startswith('LVDS')

			#Set new current device
			current_device={
				'name':name,
				'state':line[1],
				'primary':primary,
				'active':active,
				'modes':[],
				'frequency':None,
				'internal':internal
				}

	#Added last listed device (loop breaks before this)
	if current_device is not None:
		devices.append(current_device)

	return devices

#Gets lid info from /proc.
#  Returns an array of booleans.
def get_lid_info():
	dpath='/proc/acpi/button/lid/'
	lids=[]
	for fname in os.listdir(dpath):
		fpath=os.path.join(dpath,fname,'state')
		fd=open(fpath,'rb')
		data=fd.read().decode('ascii','ignore').strip()
		fd.close()
		data=data.split(':')
		if len(data)==2 and data[0].strip()=='state':
			opened=data[1].strip()
			if opened=='closed':
				opened=False
			elif opened=='open':
				opened=True
			else:
				opened=None
			lids.append(opened)
	return lids

#Uses feh to reset your wallpaper when moving the screen around.
def set_wallpaper(wallpaper_path):
	try:
		if wallpaper_path is not None:
			subprocess.check_output(['feh','--bg-fill',wallpaper_path])
	except Exception as error:
		print(error)

#Gets internal and external device object from xrandr output via
#  the given names.
#  Returns internal,external objects (or Nones if they cannot be found).
def get_internal_external(internal_name,external_name):
	internal=None
	external=None
	for info in get_xrandr_info():
		if internal is not None and external is not None:
			break
		if info['name']==internal_name:
			internal=info
		if info['name']==external_name:
			external=info
	return internal,external

def set_xrandr(name,state=True,primary=None,mode=None,offset=None,pos=None,custom=[]):
	args=['xrandr','--output',name]

	if state is not None:
		if state:
			args.append('--auto')
		else:
			args.append('--off')

	if mode is not None:
		args.append('--mode')
		args.append(mode)

	if primary is not None:
		if primary:
			args.append('--primary')
		else:
			args.append('--noprimary')

	if pos is not None:
		args.append('--pos')
		args.append('%dx%d'%pos)

	if type(custom) is list:
		args+=custom

	try:
		print('"%s"'%'" "'.join(args))
		subprocess.check_output(args)
	except Exception as error:
		print(error)

#Main
if __name__=='__main__':

	config_fpath='~/.config/openbox_auto_resolution.conf'
	try:
		fd=open(os.path.expanduser(config_fpath),'r')
		config=fd.read()
		fd.close()
		config=json.loads(config)
		for device in config['devices']:
			if 'custom' not in config['devices'][device]:
				config['devices'][device]['custom']=[]
	except FileNotFoundError as error:
		config={'devices':{}}

	#Validate args
	if len(sys.argv)<3 or len(sys.argv)>4:
		print('Usage: %s internal_device external_device [feh_wallpaper_path]')
		print('  Example: %s eDP1 DP1 /home/mittens/Pictures/catbox.png')
		exit(-1)

	#Device names to use for internal and external
	internal_name=sys.argv[1]
	external_name=sys.argv[2]
	if internal_name not in config['devices']:
		config['devices'][internal_name]={'mode':None,'custom':[]}
	if external_name not in config['devices']:
		config['devices'][external_name]={'mode':None,'custom':[]}

	#Path to whatever wallpaper is used (to use with feh)
	wallpaper_path=None
	if len(sys.argv)==4:
		wallpaper_path=sys.argv[3]
		if not os.path.exists(wallpaper_path):
			print('Wallpaper "%s" does not exist.'%wallpaper_path)
			exit(-2)

	#Variable used to keep track of if we changed things
	have_changed=True

	#Daemon loop
	while True:

		#Give the cpu a break
		time.sleep(1)

		#Get the lid check
		#  If one lid is open, they all are...how often are
		#  we going to have more than one lid?
		lid_is_open=False
		for opened in get_lid_info():
			if opened:
				lid_is_open=True
				break

		#Get the two devices
		internal,external=get_internal_external(internal_name,external_name)

		#Internal device isn't valid - exit
		if internal is None:
			print('Could not find internal "%s".'%internal)
			exit(-3)

		#External device isn't valid - exit
		if external is None:
			print('Could not find external "%s".'%external)
			exit(-4)

		#For debugging...
		status_str='lid: %d|have_changed: %d|int_act: %d|int_pri: %d|ext_act: %d|ext_pri: %d|ext_state: %s'%(lid_is_open,have_changed,internal['active'] is not None,internal['primary'],external['active'] is not None,external['primary'],external['state'])
		#print(status_str)

		#No external device connected
		if external['state']=='disconnected':

			#Internal isn't primary or we've changed something (aka, activated the external screen)
			if not internal['primary'] or have_changed:
				print('External display was unplugged!')
				set_xrandr(external_name,state=False,primary=False,custom=config['devices'][internal_name]['custom'])
				set_xrandr(internal_name,state=True,primary=True,mode=config['devices'][internal_name]['mode'],custom=config['devices'][external_name]['custom'])
				set_wallpaper(wallpaper_path)
				have_changed=False

		#External device is plugged in
		else:

			#Lid is open, or we came from an unplugged state, and either the internal display isn't active or isn't primary
			#  So we'll turn the internal display on, make it primary, and extend to the external display (to the right).
			if (lid_is_open or not have_changed) and (internal['active'] is None or not internal['primary']):
				print('Lid is open and screen is not active! %s'%status_str)
				set_xrandr(internal_name,state=True,primary=True,mode=config['devices'][internal_name]['mode'],custom=config['devices'][internal_name]['custom'])
				internal,external=get_internal_external(internal_name,external_name)
				set_xrandr(external_name,pos=(internal['active']['w'],0),custom=config['devices'][external_name]['custom'])
				set_wallpaper(wallpaper_path)
				have_changed=True

			#Lid is closed, or we came from an unplugged state, and either the internal display is active or is primary.
			#  So we'll turn the internal display off and turn the external display on and primary.
			elif (not lid_is_open or not have_changed) and (internal['active'] is not None or internal['primary']):
				print('Lid is closed and screen is active!')
				set_xrandr(internal_name,state=False,custom=config['devices'][internal_name]['custom'])
				set_xrandr(external_name,state=True,primary=True,mode=config['devices'][external_name]['mode'],custom=config['devices'][external_name]['custom'])
				set_wallpaper(wallpaper_path)
				have_changed=True
